pipeline {
     agent any

     tools {
	maven 'MAVEN381'
	jdk 'JAVA11'
     }
     stages {
          stage('Clone') {
              steps {
		git url: 'https://github.com/tektutor/devops-june-2021.git'
	      }
	  }
          stage('Compile') {
		steps {
			sh 'mvn clean compile'
		}
	  }
          stage('Unit Test') {
		steps {
			sh 'mvn test'
		}
	  }
          stage('Package') {
		steps {
			sh 'mvn package'
		}
	  }
          stage('Install') {
		steps {
			sh 'mvn install'
		}
	  }
	}
}
