pipeline {
     agent any

     tools {
	maven 'MAVEN381'
	jdk 'JAVA11'
     }
     stages {
          stage('Clone') {
              steps {
		git url: 'https://github.com/tektutor/devops-june-2021.git'
	      }
	  }
          stage('Compile') {
		steps {
			dir('Day5/JenkinsFilePipeline') {
				sh "pwd"
				sh 'mvn clean compile'
			}
		}
	  }
          stage('Unit Test') {
		steps {
			sh "pwd"
			dir('Day5/JenkinsFilePipeline') {
				sh "pwd"
			}
			sh "pwd"
			sh 'mvn test'
		}
	  }
          stage('Package') {
		steps {
			sh "pwd"
			dir('Day5/JenkinsFilePipeline') {
				sh "pwd"
			}
			sh "pwd"
			sh 'mvn package'
		}
	  }
          stage('Install') {
		steps {
			sh "pwd"
			dir('Day5/JenkinsFilePipeline') {
				sh "pwd"
			}
			sh "pwd"
			sh 'mvn install'
		}
	  }
	}
}
